---
title: "Zen demo site"
baseURL: "https://zen-demo.xdeb.org/"
theme: "github.com/frjo/hugo-theme-zen/v3"
languageCode: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
author:
  name: "Fredrik Jonsson"
  url: "https://xdeb.org"

markup:
  goldmark:
    renderer:
      unsafe: true

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML","RSS", "JSON", "SearchIndex"]
  section: ["HTML","RSS", "JSON"]

params:
  contact: "frjo@xdeb.org"
  copyright: '<!--Creative Commons License-->This site is licensed under a <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a> licence.<!--/Creative Commons License-->'
  description: "The zen theme for Hugo demo site."
  dateformat: "2 January, 2006"
  favicon: "apple-touch-icon.png"
  feedlinks: true
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  imageMaxWidth: 400
  logoWidth: 64
  mobileMenu: true
  poweredby: true
  realfavicongenerator: true
  sidebar: true
  submitted: true

languages:
  en:
    weight: 1
    languageName: "English"
    languageCode: "en-GB"
    contentDir: content/en
  sv:
    weight: 2
    languageName: "Svenska"
    languageCode: "sv-SE"
    contentDir: content/sv
